name: flutter_gif
description: gif image widget help to control gif progress,speed,repeat frames .
version: 0.0.5
homepage: https://github.com/saytoonz/flutter_gif

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
